<div style="float:right; padding-top: 15px; padding-right: 15px">
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="250">
        </a>
    </div>
</div>

# Numpy

In [1]:
import numpy as np

The basic data structures in Numpy are arrays, which can be used to represent tabular data. You can think of arrays as lists of lists.
The size of an array is the total number of elements in every list. The shape of an array is the size of the array along each dimension

In [3]:
[0.0, 0.0]

[0.0, 0.0]

In [2]:
np.zeros(2)

array([0., 0.])

In [4]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a = np.zeros((3,4,2))

a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [8]:
print(len(a))
print(a.size)
print(a.shape)

3
24
(3, 4, 2)


In [9]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [10]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
# range [0,1]
a = np.random.random((10,4))

a

array([[0.17741488, 0.81198818, 0.03705468, 0.57650362],
       [0.53893581, 0.2407619 , 0.70899726, 0.33952072],
       [0.60630087, 0.63603536, 0.30971671, 0.60734397],
       [0.7970122 , 0.73324374, 0.55496322, 0.31405838],
       [0.82912549, 0.87675528, 0.28913195, 0.21384496],
       [0.223912  , 0.69301205, 0.55848084, 0.44017542],
       [0.51358269, 0.22355999, 0.00453628, 0.10104318],
       [0.77783929, 0.72871798, 0.95315989, 0.74825735],
       [0.06818127, 0.27804089, 0.4069172 , 0.48254324],
       [0.06980057, 0.43861641, 0.57147857, 0.30231182]])

In [39]:
int(a[0][1] * 100)

31

In [45]:
np.random.randint(low=0, high=100, size=(10,4))

array([[69, 65, 13, 55],
       [17, 38, 85, 53],
       [ 1, 43, 33, 72],
       [65, 50, 98, 26],
       [82, 27,  5, 46],
       [59, 46,  3,  7],
       [37, 74, 65,  1],
       [58, 73, 70, 35],
       [74, 68,  3, 99],
       [58, 79, 38, 94]])

In [52]:
a

array([[0.17741488, 0.81198818, 0.03705468, 0.57650362],
       [0.53893581, 0.2407619 , 0.70899726, 0.33952072],
       [0.60630087, 0.63603536, 0.30971671, 0.60734397],
       [0.7970122 , 0.73324374, 0.55496322, 0.31405838],
       [0.82912549, 0.87675528, 0.28913195, 0.21384496],
       [0.223912  , 0.69301205, 0.55848084, 0.44017542],
       [0.51358269, 0.22355999, 0.00453628, 0.10104318],
       [0.77783929, 0.72871798, 0.95315989, 0.74825735],
       [0.06818127, 0.27804089, 0.4069172 , 0.48254324],
       [0.06980057, 0.43861641, 0.57147857, 0.30231182]])

In [56]:
a.size

40

In [53]:
np.reshape(a, a.size)

array([0.17741488, 0.81198818, 0.03705468, 0.57650362, 0.53893581,
       0.2407619 , 0.70899726, 0.33952072, 0.60630087, 0.63603536,
       0.30971671, 0.60734397, 0.7970122 , 0.73324374, 0.55496322,
       0.31405838, 0.82912549, 0.87675528, 0.28913195, 0.21384496,
       0.223912  , 0.69301205, 0.55848084, 0.44017542, 0.51358269,
       0.22355999, 0.00453628, 0.10104318, 0.77783929, 0.72871798,
       0.95315989, 0.74825735, 0.06818127, 0.27804089, 0.4069172 ,
       0.48254324, 0.06980057, 0.43861641, 0.57147857, 0.30231182])

In [57]:
np.reshape(a, (20,2))

array([[0.17741488, 0.81198818],
       [0.03705468, 0.57650362],
       [0.53893581, 0.2407619 ],
       [0.70899726, 0.33952072],
       [0.60630087, 0.63603536],
       [0.30971671, 0.60734397],
       [0.7970122 , 0.73324374],
       [0.55496322, 0.31405838],
       [0.82912549, 0.87675528],
       [0.28913195, 0.21384496],
       [0.223912  , 0.69301205],
       [0.55848084, 0.44017542],
       [0.51358269, 0.22355999],
       [0.00453628, 0.10104318],
       [0.77783929, 0.72871798],
       [0.95315989, 0.74825735],
       [0.06818127, 0.27804089],
       [0.4069172 , 0.48254324],
       [0.06980057, 0.43861641],
       [0.57147857, 0.30231182]])

In [60]:
np.reshape(a, (7,8))

ValueError: cannot reshape array of size 40 into shape (7,8)

In [61]:
# 2*2*2*5 = a.size
np.reshape(a, (2, 2, 2, 5))

array([[[[0.17741488, 0.81198818, 0.03705468, 0.57650362, 0.53893581],
         [0.2407619 , 0.70899726, 0.33952072, 0.60630087, 0.63603536]],

        [[0.30971671, 0.60734397, 0.7970122 , 0.73324374, 0.55496322],
         [0.31405838, 0.82912549, 0.87675528, 0.28913195, 0.21384496]]],


       [[[0.223912  , 0.69301205, 0.55848084, 0.44017542, 0.51358269],
         [0.22355999, 0.00453628, 0.10104318, 0.77783929, 0.72871798]],

        [[0.95315989, 0.74825735, 0.06818127, 0.27804089, 0.4069172 ],
         [0.48254324, 0.06980057, 0.43861641, 0.57147857, 0.30231182]]]])

In [62]:
np.reshape(a, (a.size, 1))

array([[0.17741488],
       [0.81198818],
       [0.03705468],
       [0.57650362],
       [0.53893581],
       [0.2407619 ],
       [0.70899726],
       [0.33952072],
       [0.60630087],
       [0.63603536],
       [0.30971671],
       [0.60734397],
       [0.7970122 ],
       [0.73324374],
       [0.55496322],
       [0.31405838],
       [0.82912549],
       [0.87675528],
       [0.28913195],
       [0.21384496],
       [0.223912  ],
       [0.69301205],
       [0.55848084],
       [0.44017542],
       [0.51358269],
       [0.22355999],
       [0.00453628],
       [0.10104318],
       [0.77783929],
       [0.72871798],
       [0.95315989],
       [0.74825735],
       [0.06818127],
       [0.27804089],
       [0.4069172 ],
       [0.48254324],
       [0.06980057],
       [0.43861641],
       [0.57147857],
       [0.30231182]])

In [63]:
print(a.shape)
print(a.size)

(10, 4)
40


In [64]:
a

array([[0.17741488, 0.81198818, 0.03705468, 0.57650362],
       [0.53893581, 0.2407619 , 0.70899726, 0.33952072],
       [0.60630087, 0.63603536, 0.30971671, 0.60734397],
       [0.7970122 , 0.73324374, 0.55496322, 0.31405838],
       [0.82912549, 0.87675528, 0.28913195, 0.21384496],
       [0.223912  , 0.69301205, 0.55848084, 0.44017542],
       [0.51358269, 0.22355999, 0.00453628, 0.10104318],
       [0.77783929, 0.72871798, 0.95315989, 0.74825735],
       [0.06818127, 0.27804089, 0.4069172 , 0.48254324],
       [0.06980057, 0.43861641, 0.57147857, 0.30231182]])

In [65]:
# first row
a[0]

array([0.17741488, 0.81198818, 0.03705468, 0.57650362])

In [74]:
a[0:2]

array([[0.17741488, 0.81198818, 0.03705468, 0.57650362],
       [0.53893581, 0.2407619 , 0.70899726, 0.33952072]])

In [66]:
# first column
a[:,0]

array([0.17741488, 0.53893581, 0.60630087, 0.7970122 , 0.82912549,
       0.223912  , 0.51358269, 0.77783929, 0.06818127, 0.06980057])

In [67]:
a[4,2]

0.2891319451366323

In [68]:
a[4][2]

0.2891319451366323

In [85]:
a

array([[0.17741488, 0.81198818, 0.03705468, 0.57650362],
       [0.53893581, 0.2407619 , 0.70899726, 0.33952072],
       [0.60630087, 0.63603536, 0.30971671, 0.60734397],
       [0.7970122 , 0.73324374, 0.55496322, 0.31405838],
       [0.82912549, 0.87675528, 0.28913195, 0.21384496],
       [0.223912  , 0.69301205, 0.55848084, 0.44017542],
       [0.51358269, 0.22355999, 0.00453628, 0.10104318],
       [0.77783929, 0.72871798, 0.95315989, 0.74825735],
       [0.06818127, 0.27804089, 0.4069172 , 0.48254324],
       [0.06980057, 0.43861641, 0.57147857, 0.30231182]])

In [86]:
a[2:5,1:3]

array([[0.63603536, 0.30971671],
       [0.73324374, 0.55496322],
       [0.87675528, 0.28913195]])

In [87]:
a[2:5,1:3][1,1]

0.5549632188853331

In [88]:
a[3,2]

0.5549632188853331

In [81]:
lst_lst = [[1,2],[3,4],[5,6],[7,8]]

print(lst_lst)

# list of list is not designed to easily access to inner elements (numpy is the goto)
lst_lst[0][1]

[[1, 2], [3, 4], [5, 6], [7, 8]]


2

In [90]:
a

array([[0.17741488, 0.81198818, 0.03705468, 0.57650362],
       [0.53893581, 0.2407619 , 0.70899726, 0.33952072],
       [0.60630087, 0.63603536, 0.30971671, 0.60734397],
       [0.7970122 , 0.73324374, 0.55496322, 0.31405838],
       [0.82912549, 0.87675528, 0.28913195, 0.21384496],
       [0.223912  , 0.69301205, 0.55848084, 0.44017542],
       [0.51358269, 0.22355999, 0.00453628, 0.10104318],
       [0.77783929, 0.72871798, 0.95315989, 0.74825735],
       [0.06818127, 0.27804089, 0.4069172 , 0.48254324],
       [0.06980057, 0.43861641, 0.57147857, 0.30231182]])

In [109]:
np.random.choice(a[:,1])

0.7287179817381964

In [116]:
a.shape

(10, 4)

In [112]:
np.random.choice(a)

ValueError: a must be 1-dimensional

In [111]:
np.random.choice(np.reshape(a, a.size))

0.2235599883941436

In [117]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
lst_lst.size

AttributeError: 'list' object has no attribute 'size'

In [119]:
d.size

9

In [120]:
lst_lst.shape

AttributeError: 'list' object has no attribute 'shape'

In [121]:
d.shape

(3, 3)

In [122]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9,10]]
unbalanced = np.array(lst_lst)
unbalanced

/home/ubuntu/miniconda3/envs/ironhack_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 10])],
      dtype=object)

In [123]:
unbalanced.shape

(3,)

In [124]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
np.sum(d)

45

In [126]:
np.sum(d[:,0])

12

In [127]:
np.sum(d[1,:])

15

In [128]:
np.sum(d[1])

15

In [129]:
d[1] == d[1,:]

array([ True,  True,  True])

In [130]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
np.sum(d, axis=0)

array([12, 15, 18])

In [134]:
np.sum(d, axis=1)

array([ 6, 15, 24])

In [135]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
np.mean(d)

5.0

In [137]:
np.mean(d, axis=0)

array([4., 5., 6.])

In [138]:
np.mean(d, axis=1)

array([2., 5., 8.])

## Operator overload

In [139]:
# 2+2 = 4
# 'hola' + 'quetal' = 'holaquetal'

In [140]:
x = np.array([[1,2], [1,0]])
x

array([[1, 2],
       [1, 0]])

In [141]:
y = np.array([[1,2], [1,1]])
y

array([[1, 2],
       [1, 1]])

In [142]:
x + y

array([[2, 4],
       [2, 1]])

In [143]:
np.add(x,y)

array([[2, 4],
       [2, 1]])

In [144]:
np.concatenate([x, y])

array([[1, 2],
       [1, 0],
       [1, 2],
       [1, 1]])

In [147]:
print(x)
print(y)

[[1 2]
 [1 0]]
[[1 2]
 [1 1]]


In [145]:
x - y

array([[ 0,  0],
       [ 0, -1]])

In [146]:
np.subtract(x,y)

array([[ 0,  0],
       [ 0, -1]])

In [148]:
x * y

array([[1, 4],
       [1, 0]])

In [149]:
np.multiply(x,y)

array([[1, 4],
       [1, 0]])

In [150]:
x / y

array([[1., 1.],
       [1., 0.]])

In [151]:
np.divide(x,y)

array([[1., 1.],
       [1., 0.]])

In [152]:
x

array([[1, 2],
       [1, 0]])

In [153]:
y

array([[1, 2],
       [1, 1]])

In [154]:
np.matmul(x,y)

array([[3, 4],
       [1, 2]])

<div style="padding-top: 25px; float: right">
    <div>    
        <i>&nbsp;&nbsp;© Copyright by</i>
    </div>
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="125">
        </a>
    </div>
</div>